<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRecordRepository extends EntityRepository
{
}
