app_track_api:
    resource: "@AppBundle/Controller/TrackRESTController.php"
    type:   rest
    prefix:   /api

app_playlist_api:
    resource: "@AppBundle/Controller/PlaylistRESTController.php"
    type:   rest
    prefix:   /api

app_mediatype_api:
    resource: "@AppBundle/Controller/MediatypeRESTController.php"
    type:   rest
    prefix:   /api

app_invoiceline_api:
    resource: "@AppBundle/Controller/InvoicelineRESTController.php"
    type:   rest
    prefix:   /api

app_invoice_api:
    resource: "@AppBundle/Controller/InvoiceRESTController.php"
    type:   rest
    prefix:   /api

app_genre_api:
    resource: "@AppBundle/Controller/GenreRESTController.php"
    type:   rest
    prefix:   /api

app_employee_api:
    resource: "@AppBundle/Controller/EmployeeRESTController.php"
    type:   rest
    prefix:   /api

app_customer_api:
    resource: "@AppBundle/Controller/CustomerRESTController.php"
    type:   rest
    prefix:   /api

app_artist_api:
    resource: "@AppBundle/Controller/ArtistRESTController.php"
    type:   rest
    prefix:   /api

app_album_api:
    resource: "@AppBundle/Controller/AlbumRESTController.php"
    type:   rest
    prefix:   /api

proxy:
    resource: "@ProxyBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting
sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile
sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register
sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin