# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.admin.album:
        class: AppBundle\Admin\AlbumAdmin
        arguments: [~, AppBundle\Entity\Album, AppBundle:AlbumAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Album }

    app.admin.artist:
        class: AppBundle\Admin\ArtistAdmin
        arguments: [~, AppBundle\Entity\Artist, AppBundle:ArtistAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Artist }

    app.admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [~, AppBundle\Entity\Customer, AppBundle:CustomerAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Customer }

    app.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, AppBundle:EmployeeAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Employee }

    app.admin.genre:
        class: AppBundle\Admin\GenreAdmin
        arguments: [~, AppBundle\Entity\Genre, AppBundle:GenreAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Genre }

    app.admin.invoice:
        class: AppBundle\Admin\InvoiceAdmin
        arguments: [~, AppBundle\Entity\Invoice, AppBundle:InvoiceAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Invoice }

    app.admin.invoiceline:
        class: AppBundle\Admin\InvoicelineAdmin
        arguments: [~, AppBundle\Entity\Invoiceline, AppBundle:InvoicelineAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Invoiceline }

    app.admin.mediatype:
        class: AppBundle\Admin\MediatypeAdmin
        arguments: [~, AppBundle\Entity\Mediatype, AppBundle:MediatypeAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mediatype }

    app.admin.playlist:
        class: AppBundle\Admin\PlaylistAdmin
        arguments: [~, AppBundle\Entity\Playlist, AppBundle:PlaylistAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Playlist }

    app.admin.track:
        class: AppBundle\Admin\TrackAdmin
        arguments: [~, AppBundle\Entity\Track, AppBundle:TrackAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Track }
