# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.admin.movie:
        class: AppBundle\Admin\MovieAdmin
        arguments: [~, AppBundle\Entity\Movie, AppBundle:MovieAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Movie }

    app.admin.tag:
        class: AppBundle\Admin\TagAdmin
        arguments: [~, AppBundle\Entity\Tag, AppBundle:TagAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Tag }

    app.admin.actor:
        class: AppBundle\Admin\ActorAdmin
        arguments: [~, AppBundle\Entity\Actor, AppBundle:ActorAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Actor }

    app.admin.movie_quality:
        class: AppBundle\Admin\MovieQualityAdmin
        arguments: [~, AppBundle\Entity\MovieQuality, AppBundle:MovieQualityAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: MovieQuality }

    app.admin.feedback_record:
        class: AppBundle\Admin\FeedbackRecordAdmin
        arguments: [~, AppBundle\Entity\FeedbackRecord, AppBundle:FeedbackRecordAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Dot-44, label: FeedbackRecord }

    app.admin.author:
        class: AppBundle\Admin\AuthorAdmin
        arguments: [~, AppBundle\Entity\Author, AppBundle:AuthorAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Author }

    app.admin.book:
        class: AppBundle\Admin\BookAdmin
        arguments: [~, AppBundle\Entity\Book, AppBundle:BookAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Book }
