parameters:
    proxy.controller.class: ProxyBundle\Controller\ProxyController
    proxy.routing_loader.class: ProxyBundle\Routing\ProxyLoader
    proxy.client.class: GuzzleHttp\Client

services:
    proxy.controller:
        class: '%proxy.controller.class%'
        calls:
            - [ setContainer, [ "@service_container" ] ]

    proxy.routing_loader:
        class: '%proxy.routing_loader.class%'
        tags:
            - { name: routing.loader }

    proxy.client:
        class: '%proxy.client.class%'
        abstract: true
