AppBundle\Entity\GoodCards:
    type: entity
    table: good_cards
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        goodId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: good_id
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        image:
            type: binary
            nullable: true
    lifecycleCallbacks: {  }
