AppBundle\Entity\Offers:
    type: entity
    table: offers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        cost:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
