AppBundle\Entity\Orders:
    type: entity
    table: orders
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    oneToOne:
        customerId:
           targetEntity: Customer
           joinColumn:
               name: customer_id
               referencedColumnName: id
    manyToMany:
        goods:
          targetEntity: Goods
          joinTable:
            name: orders_goods
            joinColumns:
              order_id:
                referencedColumnName: id
            inverseJoinColumns:
              good_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
