AppBundle\Entity\ShopData:
    type: entity
    table: shop_data
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        apiKeys:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: api_keys
    lifecycleCallbacks: {  }
